---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/signup":
    post:
      summary: User Registration
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: OK
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - name
                  - email
                  - password
        required: true
  "/login":
    post:
      summary: User Login
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: created
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
        required: true
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
